alias lla='ls -Al'
alias mountt='mount | column -t'
alias weather='curl wttr.in'
alias vi='vim'
alias colortable='ruby -e "$(curl -fsSL https://raw.githubusercontent.com/gawin/bash-colors-256/master/colors)"'
